version: "3.8"
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - app-network
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - app-network
networks:
  app-network:
