name: Desafio Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: (Opcional) Compilar el proyecto
      - name: Run build
        run: npm run build

      # Paso 5: Ejecutar pruebas (Opcional)
      - name: Run tests
        run: npm test

      # Paso 6: Configurar Docker para Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 7: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 8: Construir y publicar la imagen Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .                # Contexto donde se encuentra el Dockerfile
          file: ./Dockerfile        # Ruta del Dockerfile
          push: true                # Publicar la imagen
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/docker push yascf/monitorig-app:latest
            ${{ secrets.DOCKER_USERNAME }}/docker push yascf/monitorig-app:${{ github.sha }}
